update actions.yaml file

diff --git a/.github/workflows/actions.yaml b/.github/workflows/actions.yaml
--- a/.github/workflows/actions.yaml
+++ b/.github/workflows/actions.yaml
@@ -18,12 +18,12 @@ jobs:
         run: eval $(minikube docker-env)
       - name: Build and Push Backend Docker Image
         run: |
-          docker build -t huitingfeng/appbackend:9.0 ./AppBackEnd
+          docker build --no-cache -t huitingfeng/appbackend:9.0 ./AppBackEnd
           echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
           docker push huitingfeng/appbackend:9.0
       - name: Build and Push Frontend Docker Image
         run: |
-          docker build -t huitingfeng/appfrontend:17.0 ./AppFrontEnd
+          docker build --no-cache -t huitingfeng/appfrontend:17.0 ./AppFrontEnd
           docker push huitingfeng/appfrontend:17.0
       - name: Deploy to Minikube
         run: |
@@ -35,10 +35,12 @@ jobs:
       - name: Verify MySQL Connection
         run: |
           MYSQL_POD=$(kubectl get pods -l app=mysql -o jsonpath="{.items[0].metadata.name}")
-          kubectl exec $MYSQL_POD -- mysqladmin -u root -pHuiting123.. status
+          kubectl exec $MYSQL_POD -- mysqladmin -h mysql -P 3306 -u root -pHuiting123.. status
       - name: Get and Test Service URLs
         run: |
           minikube service list
           BACKEND_URL=$(minikube service appbackend-service --url)
           echo "Backend service URL: $BACKEND_URL"
-          # Add any tests or curls to your services here
+          # Test the backend service using curl
+          echo "Testing backend service at $BACKEND_URL"
+          curl -sSf $BACKEND_URL -o /dev/null || echo "Curl request to backend service failed"
